<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Apk4CategoryTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('apk4_category')->delete();
        
        \DB::table('apk4_category')->insert(array (
            0 => 
            array (
                'id' => 30,
                'name' => 'Battle Arena',
                'catalog' => 'battle',
                'seo_title' => 'Battle Arena Games for Android - Free Download from',
                'seo_keywords' => 'battle arena games for android,battle arena games download',
                'seo_description' => 'Battle Arena Games for Android can be quickly downloaded for free on apk42. Download Battle Arena Games on apk4 for non-stop action-packed fun! Battle Arena Games are intense multiplayer games where you compete against other players in epic battles. With stunning graphics and addictive gameplay, these games will keep you hooked for hours.',
                'pid' => 30,
                'sort_order' => 0,
                'addtime' => 1711442513,
                'uptime' => 1711446829,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 101,
                'classify' => 1,
                'is404' => 2,
            ),
            1 => 
            array (
                'id' => 31,
                'name' => 'Tower Defense',
                'catalog' => 'defense',
                'seo_title' => 'Tower Defense Games for Android - Free Download from',
                'seo_keywords' => 'tower defense games android,tower defense games download',
                'seo_description' => 'Tower Defense Games for Android can be quickly downloaded for free on apk42. Tower Defense Games are strategic games where players defend their base or territory from waves of enemies. These games challenge your thinking and planning skills while providing hours of fun. With diverse levels and challenges, Tower Defense Games offer endless entertainment. Downloading these games allows you to enjoy thrilling gameplay anytime, anywhere.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711442671,
                'uptime' => 1711501042,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            2 => 
            array (
                'id' => 32,
                'name' => 'Management Simulation',
                'catalog' => 'simulation',
                'seo_title' => 'Management Simulation Games for Android - Free Download from',
                'seo_keywords' => 'management simulation games android,management simulation games download',
                'seo_description' => 'Management Simulation Games for Android can be quickly downloaded for free on apk42. Management Simulation Games let you run your own virtual world, like a city or a business. You make decisions, manage resources, and solve problems. It\'s like being in charge of your own mini-universe! Downloading these games is a smart move because they\'re not just entertaining—they also boost your brainpower.',
                'pid' => 32,
                'sort_order' => 0,
                'addtime' => 1711442740,
                'uptime' => 1711446840,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 101,
                'classify' => 1,
                'is404' => 2,
            ),
            3 => 
            array (
                'id' => 33,
                'name' => 'Shooter',
                'catalog' => 'shoot',
                'seo_title' => 'Shooter Games for Android - Free Download from',
                'seo_keywords' => 'shooter games download apk,shooter games for android',
                'seo_description' => 'Shooter Games for Android can be quickly downloaded for free on apk42. Shooter Games are all about fast-paced action, strategic thinking, and adrenaline-pumping excitement. With these games, you can step into the shoes of a sharpshooter and take on thrilling challenges. Whether you\'re battling aliens, zombies, or enemy soldiers, Shooter Games offer an immersive experience that keeps you hooked for hours.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711442838,
                'uptime' => 1711501324,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            4 => 
            array (
                'id' => 34,
                'name' => 'Action Adventure',
                'catalog' => 'action',
                'seo_title' => 'Action Adventure Games for Android - Free Download from',
                'seo_keywords' => 'action adventure games android,action adventure games android download',
                'seo_description' => 'Action Adventure Games for Android can be quickly downloaded for free on apk42. Action Adventure Games are all about adrenaline-pumping experiences, where you embark on epic quests, face daring challenges, and explore immersive worlds. Downloading these games is your ticket to endless excitement and entertainment. Whether you\'re a fan of daring escapades or epic battles, our collection has something for everyone. Get ready to immerse yourself in thrilling adventures right at your fingertips.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711442874,
                'uptime' => 1711501329,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            5 => 
            array (
                'id' => 35,
            'name' => 'Role Playing (RPG)',
                'catalog' => 'rpg',
                'seo_title' => 'Role Playing Games for Android - Free Download from',
                'seo_keywords' => 'role playing games for android,role playing games apk download',
            'seo_description' => 'Role Playing Games for Android can be quickly downloaded for free on apk42. Role Playing Games (RPGs) are games where you take on a character\'s role, like a hero or a wizard, and go on adventures. Why download RPGs? They\'re thrilling, letting you escape into exciting realms where you make choices and solve challenges. Plus, they\'re great for your creativity and problem-solving skills.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711442917,
                'uptime' => 1711501295,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            6 => 
            array (
                'id' => 36,
                'name' => 'Puzzle',
                'catalog' => 'puzzle',
                'seo_title' => 'Puzzle Games for Android - Free Download from',
                'seo_keywords' => 'puzzle games app,puzzle games app download',
                'seo_description' => 'Puzzle Games for Android can be quickly downloaded for free on apk42. Puzzle games are brain-teasers that test your problem-solving skills. With various levels of difficulty, they keep your mind sharp and entertained. From matching colors to solving riddles, there\'s a puzzle game for everyone. Why download? Well, puzzle games are not just about fun; they also help improve memory, concentration, and logic skills. Plus, they\'re great for passing time and relieving stress.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711442959,
                'uptime' => 1711501334,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            7 => 
            array (
                'id' => 37,
                'name' => 'Strategy Card',
                'catalog' => 'strategy',
                'seo_title' => 'Strategy Card Games for Android - Free Download from',
                'seo_keywords' => 'strategy card games android,strategy card games apk download',
                'seo_description' => 'Strategy Card Games for Android can be quickly downloaded for free on apk42. Strategy card games are exciting challenges where you use cards to plan your moves and outsmart opponents. These games offer a fun way to exercise your brain and improve strategic thinking skills. By downloading strategy card games, you can enjoy hours of entertainment while honing your decision-making abilities.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443026,
                'uptime' => 1711501339,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            8 => 
            array (
                'id' => 38,
                'name' => 'Card',
                'catalog' => 'card',
                'seo_title' => 'Card Games for Android - Free Download from',
                'seo_keywords' => 'card games apk download,card games apk download',
                'seo_description' => 'Card Games for Android can be quickly downloaded for free on apk42. Card games are classic, entertaining games played with a deck of cards. They\'re perfect for passing time and having fun with friends or on your own. With a variety of card games available on apk42, you can enjoy classics like Poker, Solitaire, and Uno, or discover new favorites.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443099,
                'uptime' => 1711501344,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            9 => 
            array (
                'id' => 39,
                'name' => 'Arcade',
                'catalog' => 'arcade',
                'seo_title' => 'Arcade Games for Android - Free Download from',
                'seo_keywords' => 'arcade games android,arcade games android apk',
                'seo_description' => 'Arcade Games for Android can be quickly downloaded for free on apk42. Arcade games are classic and exciting games that bring joy and entertainment to everyone. From timeless favorites like Pac-Man to modern hits like Subway Surfers, there\'s something for everyone. Downloading these games gives you endless hours of enjoyment, whether you\'re looking to pass the time or challenge your friends. With simple controls and addictive gameplay, Arcade Games are perfect for players of all ages.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443141,
                'uptime' => 1711501349,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            10 => 
            array (
                'id' => 40,
                'name' => 'Music',
                'catalog' => 'music',
                'seo_title' => 'Music Games for Android - Free Download from',
                'seo_keywords' => 'music games for android,music games for free',
                'seo_description' => 'Music Games for Android can be quickly downloaded for free on apk42. Music Games are interactive games where you tap along to the beat of catchy tunes. From tapping tiles to hitting notes, these games challenge your timing and coordination while enjoying your favorite songs. Downloading Music Games offers a fantastic way to unwind, boost mood, and sharpen reflexes.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443249,
                'uptime' => 1711501354,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            11 => 
            array (
                'id' => 41,
                'name' => 'Fantasy World',
                'catalog' => 'fantasy',
                'seo_title' => 'Fantasy World Games for Android - Free Download from',
                'seo_keywords' => 'fantasy world game app,fantasy world game online',
                'seo_description' => 'Fantasy World Games for Android can be quickly downloaded for free on apk42. Fantasy World Games transport you to fantastical worlds where anything is possible. Whether you\'re battling dragons, exploring enchanted forests, or solving puzzles in mystical lands, there\'s something for everyone. Download Fantasy World Games on apk42 for endless adventure and excitement. Immerse yourself in captivating stories, stunning visuals, and thrilling gameplay.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443312,
                'uptime' => 1711501318,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            12 => 
            array (
                'id' => 42,
                'name' => 'Speed Racing',
                'catalog' => 'racing',
                'seo_title' => 'Speed Racing Games for Android - Free Download from',
                'seo_keywords' => 'speed racing game download,speed racing game online',
                'seo_description' => 'Speed Racing Games for Android can be quickly downloaded for free on apk42. Speed Racing Games are thrilling games where you drive super-fast cars, bikes, or even planes to beat opponents and finish first. These games give you a rush of excitement and challenge your skills behind the wheel. Speed Racing Games offer non-stop action and adrenaline, perfect for anyone who loves speed and competition.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443370,
                'uptime' => 1711501312,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            13 => 
            array (
                'id' => 43,
                'name' => 'Sports',
                'catalog' => 'sport',
                'seo_title' => 'Sports Games for Android - Free Download from',
                'seo_keywords' => 'sports games apk,sports games download for android',
                'seo_description' => 'Sports Games for Android can be quickly downloaded for free on apk42. Sports Games are digital recreations of real-life sports like soccer, basketball, and racing, offering immersive experiences on your device. Whether you\'re a sports enthusiast or just looking for some entertainment, downloading Sports Games is a must. Challenge your friends, improve your skills, and experience the thrill of victory right at your fingertips.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443437,
                'uptime' => 1711501306,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            14 => 
            array (
                'id' => 44,
                'name' => 'Educational',
                'catalog' => 'education',
                'seo_title' => 'Educational Games for Android - Free Download from',
                'seo_keywords' => 'educational games apk,educational games android',
                'seo_description' => 'Educational Games for Android can be quickly downloaded for free on apk42. Educational Games are interactive apps designed to make learning enjoyable for everyone. From math puzzles to language games, these apps cover a wide range of subjects and skills. By downloading Educational Games, you can help your child improve their cognitive abilities, enhance their knowledge, and boost their academic performance.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711443503,
                'uptime' => 1711501284,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
            15 => 
            array (
                'id' => 45,
                'name' => 'Capture Memories',
                'catalog' => 'capture',
                'seo_title' => 'Capture Memories Apps for Android - Free Download from',
                'seo_keywords' => 'capture memories app,capture app download',
                'seo_description' => 'Capture Memories Apps for Android can be quickly downloaded for free on apk42. Capture Memories apps allow you to store, organize, and share your precious memories in one convenient place. With user-friendly interfaces and intuitive features, capturing and reliving special occasions becomes a breeze. Whether it\'s photos, videos, or notes, these apps ensure that no memory fades away.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711443583,
                'uptime' => 1711501266,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            16 => 
            array (
                'id' => 46,
                'name' => 'Short Video',
                'catalog' => 'short',
                'seo_title' => 'Short Video Apps for Android - Free Download from',
                'seo_keywords' => 'short video app free,short video app download',
                'seo_description' => 'Short video apps for Android can be quickly downloaded for free on apk42. Short Video apps are perfect for quick entertainment bursts, offering bite-sized videos that cater to your interests. Whether you enjoy funny clips, DIY tutorials, or informative content, Short Video apps have something for everyone. Downloading Short Video apps opens up a world of entertainment at your fingertips.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711443685,
                'uptime' => 1711501169,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            17 => 
            array (
                'id' => 47,
                'name' => 'Watch Together',
                'catalog' => 'watch',
                'seo_title' => 'Watch Together Apps for Android - Free Download from',
                'seo_keywords' => 'watch together apps free,watch together apps android',
                'seo_description' => 'Watch Together Apps for Android can be quickly downloaded for free on apk42. Watch Together apps bring friends and family closer by allowing simultaneous streaming and synchronized playback of videos. Whether it\'s catching up on favorite shows, sharing memorable moments, or simply enjoying entertainment together, Watch Together Apps make it effortless. With easy download access on apk42, you can instantly connect with loved ones no matter where they are.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711443771,
                'uptime' => 1711501260,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            18 => 
            array (
                'id' => 48,
                'name' => 'Best Budgeting',
                'catalog' => 'budget',
                'seo_title' => 'Best Budgeting Apps for Android - Free Download from',
                'seo_keywords' => 'best budgeting app android,best free budget app for android',
                'seo_description' => 'Best Budgeting Apps for Android can be quickly downloaded for free on apk42. Looking to manage your money better? Get the best budgeting apps on apk42! Budgeting apps help you track your spending, save money, and reach your financial goals. With these apps, you can easily create budgets, track expenses, and even get reminders for bills. They\'re like your personal finance assistant, making money management simple and stress-free.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711443827,
                'uptime' => 1711501254,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            19 => 
            array (
                'id' => 49,
                'name' => 'Learning',
                'catalog' => 'learn',
                'seo_title' => 'Learning Apps for Android - Free Download from',
                'seo_keywords' => 'learning app,learning app download',
                'seo_description' => 'Learning Apps for Android can be quickly downloaded for free on apk42. Learning Apps are specially designed tools that help you learn new skills, gain knowledge, and expand your horizons. Whether you\'re a student, professional, or just someone eager to learn, these apps offer a wide range of subjects and topics to explore. From languages and math to coding and cooking, there\'s something for everyone.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444018,
                'uptime' => 1711501192,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            20 => 
            array (
                'id' => 50,
                'name' => 'Best Apps for Kids',
                'catalog' => 'kids',
                'seo_title' => 'Best Apps for Kids for Android - Free Download from',
                'seo_keywords' => 'best apps for kids android,best apps for kids learning',
                'seo_description' => 'Best Apps for Kids for Android can be quickly downloaded for free on apk42. Our selection of Best Apps for Kids provides fun and educational experiences for children. From interactive games to learning tools, these apps are designed to engage and entertain young minds. Downloading these apps ensures your child\'s screen time is not only enjoyable but also enriching.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444084,
                'uptime' => 1711501161,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            21 => 
            array (
                'id' => 51,
                'name' => 'Boost Productivity',
                'catalog' => 'productivity',
                'seo_title' => 'Boost Productivity for Android - Free Download from',
                'seo_keywords' => 'boost productivity app,boost productivity app android',
                'seo_description' => 'Boost Productivity Apps for Android can be quickly downloaded for free on apk42. Boost productivity apps are tools designed to help you work smarter and get more done in less time. With these apps, you can organize tasks, manage schedules, and stay focused on your goals. By downloading Boost Productivity apps on apk42, you can unlock a world of efficiency and effectiveness right at your fingertips.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444148,
                'uptime' => 1711501246,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            22 => 
            array (
                'id' => 52,
                'name' => 'Travel & Local',
                'catalog' => 'travel',
                'seo_title' => 'Travel & Local Apps for Android - Free Download from',
                'seo_keywords' => 'travel and local apps for android,local travel app android',
                'seo_description' => 'Travel & Local Apps for Android can be quickly downloaded for free on apk42. Travel & Local apps are your passport to discovering exciting places, finding the best hotels, and navigating unfamiliar cities effortlessly. Whether you\'re planning a vacation or exploring your own hometown, Travel & Local Apps offer features like maps, hotel bookings, restaurant recommendations, and local transportation options. With just a few taps, you can access valuable information and make your travels smooth',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444237,
                'uptime' => 1711501240,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            23 => 
            array (
                'id' => 53,
                'name' => 'Dating',
                'catalog' => 'date',
                'seo_title' => 'Dating Apps for Android - Free Download from',
                'seo_keywords' => 'dating apps free,dating apps download',
                'seo_description' => 'Dating Apps for Android can be quickly downloaded for free on apk42. Dating apps are special applications you can use on your phone to meet and connect with others who are also looking for relationships or friendships. Dating apps make it easy to find people with similar interests, chat with them, and even arrange dates. Whether you\'re looking for love, companionship, or just someone to chat with, dating apps have got you covered.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444330,
                'uptime' => 1711501199,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            24 => 
            array (
                'id' => 54,
                'name' => 'Social & Communication',
                'catalog' => 'social',
                'seo_title' => 'Social & Communication Apps for Android - Free Download from',
                'seo_keywords' => 'social & communication app download,social communication apps',
                'seo_description' => 'Social & Communication Apps for Android can be quickly downloaded for free on apk42. Social & Communication apps are essential tools for staying in touch with friends, family, and colleagues. From messaging to video calls, Social & Communication apps make it easy to share moments and ideas instantly. Whether you\'re chatting with loved ones or collaborating with coworkers, these apps streamline communication and keep you connected wherever you go.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444395,
                'uptime' => 1711501205,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            25 => 
            array (
                'id' => 55,
                'name' => 'Music & Audio',
                'catalog' => 'musicnaudio',
                'seo_title' => 'Music & Audio Apps for Android - Free Download from',
                'seo_keywords' => 'music audio app free download,music audio app free',
                'seo_description' => 'Music & Audio Apps for Android can be quickly downloaded for free on apk42. Whether you\'re a music lover, podcast enthusiast, or looking for the perfect sound editing tool, we\'ve got you covered. Music & Audio Apps offer a range of features like streaming music, creating playlists, recording podcasts, and editing audio files. With these apps, you can enjoy your favorite tunes anytime, anywhere, and explore new genres effortlessly.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444582,
                'uptime' => 1711501185,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            26 => 
            array (
                'id' => 56,
                'name' => 'Video Player & Editors',
                'catalog' => 'video',
                'seo_title' => 'Video Player & Editors Apps for Android - Free Download from',
                'seo_keywords' => 'video players & editors,video players & editors download',
                'seo_description' => 'Video Player & Editors Apps for Android can be quickly downloaded for free on apk42. Media & Video Apps are tools you use on your phone or tablet to watch videos, listen to music, and view photos. They\'re super handy for entertainment and staying connected. With apk42, you can easily find and download all the top Media & Video Apps. Whether you\'re into streaming movies, listening to music, or editing videos, these apps have got you covered.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444676,
                'uptime' => 1711501233,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            27 => 
            array (
                'id' => 57,
                'name' => 'Tools',
                'catalog' => 'tools',
                'seo_title' => 'Tools Apps for Android - Free Download from',
                'seo_keywords' => 'tools app download apk,tools app for android free download',
                'seo_description' => 'Tools Apps for Android can be quickly downloaded for free on apk42. Tools Apps are designed to make your life easier. From file managers to calculators, these apps offer a wide range of functions to help you with everyday tasks. Whether you need to organize your files, calculate numbers, or even optimize your device, tools Apps have got you covered.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444753,
                'uptime' => 1711501153,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            28 => 
            array (
                'id' => 58,
                'name' => 'Shopping',
                'catalog' => 'shopping',
                'seo_title' => 'Shopping Apps for Android - Free Download from',
                'seo_keywords' => 'shopping app apk,shopping app download free',
                'seo_description' => 'Shopping Apps for Android can be quickly downloaded for free on apk42. Shopping apps bring the convenience right to your fingertips, allowing you to browse, compare prices, and purchase your favorite products with ease. With a user-friendly interface and a wide range of products available, shopping has never been simpler. Plus, with exclusive deals and discounts only available on the app, you\'ll save money while you shop.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711444840,
                'uptime' => 1711501179,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            29 => 
            array (
                'id' => 59,
                'name' => 'Reading',
                'catalog' => 'read',
                'seo_title' => 'Reading Apps for Android - Free Download from',
                'seo_keywords' => 'reading app for free,reading app for android',
                'seo_description' => 'Reading Apps for Android can be quickly downloaded for free on apk42. Reading App is designed to lets you access a vast library of books, articles, and stories right on your device. With this app, you can explore countless genres and topics, from fiction to non-fiction, all at your fingertips. Whether you\'re a bookworm or just love to read occasionally, this app is perfect for you.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711445114,
                'uptime' => 1711501146,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            30 => 
            array (
                'id' => 60,
                'name' => 'Health & Fitness',
                'catalog' => 'health',
                'seo_title' => 'Health & Fitness Apps for Android - Free Download from',
                'seo_keywords' => 'health fitness app android,health & fitness app free download',
                'seo_description' => 'Health & Fitness Apps for Android can be quickly downloaded for free on apk42. Health & Fitness apps are your personal trainers, nutrition guides, and wellness trackers all in one place. With easy access to exercise routines, healthy recipes, and progress tracking, you can take control of your health journey. Whether you\'re aiming to lose weight, build muscle, or simply improve your overall well-being, these apps offer tailored solutions to suit your needs.',
                'pid' => 62,
                'sort_order' => 0,
                'addtime' => 1711445302,
                'uptime' => 1711501138,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 2,
                'is404' => 2,
            ),
            31 => 
            array (
                'id' => 61,
                'name' => 'game',
                'catalog' => 'game',
                'seo_title' => 'Download the Best and Trending Games on Android for Free - apk42',
                'seo_keywords' => 'Games apk download, free Games download, download Games apk, Games apk downloader, Games android, Games app download',
                'seo_description' => 'Explore and download the best Android Games fast and free on apk42, including Free Fire: The Chaos, Roblox, Free Fire MAX',
                'pid' => 0,
                'sort_order' => 0,
                'addtime' => 1711501011,
                'uptime' => 1711541338,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 1,
                'classify' => 1,
                'is404' => 2,
            ),
            32 => 
            array (
                'id' => 62,
                'name' => 'app',
                'catalog' => 'app',
                'seo_title' => 'Download the Best and Trending Apps on Android for Free - apk42',
                'seo_keywords' => 'Apps apk download, free Apps download, Apps apk download, download Apps apk, Apps apk downloader, Apps android',
                'seo_description' => 'Explore and download the best Android Apps fast and free on apk42, including WhatsApp Messenger, VidMate HD Video Downloader &amp; Live TV, Messenger',
                'pid' => 0,
                'sort_order' => 0,
                'addtime' => 1711501026,
                'uptime' => 1711541346,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 1,
                'classify' => 2,
                'is404' => 2,
            ),
            33 => 
            array (
                'id' => 63,
                'name' => 'Simulation',
                'catalog' => 'Simulate',
                'seo_title' => 'Management Simulation Games for Android - Free Download from',
                'seo_keywords' => 'management simulation games android,management simulation games download',
                'seo_description' => 'Management Simulation Games for Android can be quickly downloaded for free on apk42. Management Simulation Games let you run your own virtual world, like a city or a business. You make decisions, manage resources, and solve problems. It\'s like being in charge of your own mini-universe! Downloading these games is a smart move because they\'re not just entertaining—they also boost your brainpower.',
                'pid' => 61,
                'sort_order' => 0,
                'addtime' => 1711524271,
                'uptime' => 1711524271,
                'status' => 1,
                'addadmin' => 110,
                'upadmin' => 110,
                'classify' => 1,
                'is404' => 2,
            ),
        ));
        
        
    }
}