<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Apk4AdvertpicTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('apk4_advertpic')->delete();
        
        \DB::table('apk4_advertpic')->insert(array (
            0 => 
            array (
                'id' => 1,
                'adid' => 1,
                'describe' => 'First major update since global launch! Season 7: Architects of Fate!',
                'url' => 'https://www.apk42.com/game/honor_of_kings',
                'img' => '52img/uploadimg/20240927/271742150jdf.jpg',
                'status' => 1,
                'remark' => '2769',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727430186',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'adid' => 1,
                'describe' => 'Brawl Stars brings you the exciting Solo Showdown mode',
                'url' => 'https://www.apk42.com/game/brawl_stars',
                'img' => '52img/uploadimg/20240417/17154617eblc.jpg',
                'status' => 1,
                'remark' => '9',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713339979',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'adid' => 1,
                'describe' => 'Eversoul Gameplay!',
                'url' => 'https://www.apk42.com/game/eversoul/',
                'img' => '52img/uploadimg/20240417/17155040ux4w.jpg',
                'status' => 1,
                'remark' => '312',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713340340',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'adid' => 4,
                'describe' => 'pc-首页-top游戏',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '13392,27,13453,13450,8,13473,13425,13418,13410,13414',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727430755',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'adid' => 5,
                'describe' => 'pc-首页-top应用',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '1,10,2,3,19,17,5,63,55,20',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713335798',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            5 => 
            array (
                'id' => 6,
                'adid' => 6,
                'describe' => 'pc-首页-个性化推荐',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '13258,10944,823,13503,13487,13481,13458,13454,13445,13428',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727429870',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'adid' => 7,
                'describe' => 'Shawarma Legend',
                'url' => 'https://www.apk42.com/game/shawarma_legend/',
                'img' => '52img/uploadimg/20240927/27174622r7ma.jpg',
                'status' => 1,
                'remark' => '13258',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727430393',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'adid' => 7,
                'describe' => 'Brave Nine - Tactical RPG',
                'url' => 'https://www.apk42.com/game/brave_nine_tactical_rpg/',
                'img' => '52img/uploadimg/20240927/271748103qyl.jpg',
                'status' => 1,
                'remark' => '13504',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727430492',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'adid' => 7,
                'describe' => 'X-Samkok',
                'url' => 'https://www.apk42.com/game/x_samkok',
                'img' => '52img/uploadimg/20240927/27174946rawz.jpg',
                'status' => 1,
                'remark' => '13445',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727430589',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'adid' => 8,
                'describe' => 'pc-首页-热游排行榜-热门免费',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '257,234,263,262,229,233,228,226,188',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713341778',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'adid' => 9,
                'describe' => 'pc-首页-热游排行榜-最受期待',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '160,158,163,167,147,145,144,118,137',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713341759',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'adid' => 10,
                'describe' => 'pc-首页-应用排行榜-热门免费',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '1,10,2,6,5,3,4,12,11',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713341873',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            12 => 
            array (
                'id' => 13,
                'adid' => 11,
                'describe' => 'pc-首页-应用排行榜-最受期待',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '29,33,17,8,9,18,7,32,30',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713342007',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'adid' => 12,
                'describe' => 'pc-游戏详情-好游安利',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '6,7,8,10,312,319,305,254,246,244',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344043',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'adid' => 13,
                'describe' => 'pc-应用详情-应用安利',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '4,6,12,1,2,3,29,45,41,19',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344169',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            15 => 
            array (
                'id' => 19,
                'adid' => 14,
                'describe' => 'First major update since global launch! Season 7: Architects of Fate!',
                'url' => 'https://www.apk42.com/game/honor_of_kings',
                'img' => '52img/uploadimg/20240927/27174411vv7b.jpg',
                'status' => 1,
                'remark' => '2769',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727430267',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            16 => 
            array (
                'id' => 20,
                'adid' => 14,
                'describe' => 'Brawl Stars brings you the exciting Solo Showdown mode',
                'url' => 'https://www.apk42.com/game/brawl_stars',
                'img' => '52img/uploadimg/20240417/17154617eblc.jpg',
                'status' => 1,
                'remark' => '9',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713342352',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            17 => 
            array (
                'id' => 21,
                'adid' => 14,
                'describe' => 'Eversoul Gameplay!',
                'url' => 'https://www.apk42.com/game/eversoul/',
                'img' => '52img/uploadimg/20240417/17155040ux4w.jpg',
                'status' => 1,
                'remark' => '312',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713342423',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            18 => 
            array (
                'id' => 22,
                'adid' => 17,
                'describe' => 'm-首页-top游戏',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '66,69,8,242,45,108,221,145,88',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713342660',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            19 => 
            array (
                'id' => 23,
                'adid' => 18,
                'describe' => 'm-首页-top应用',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '1,10,2,3,19,17,5,63,55,20',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713342837',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            20 => 
            array (
                'id' => 24,
                'adid' => 19,
                'describe' => 'm-首页-个性化推荐',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '13258,10944,823,13503,13487,13481,13458,13454,13445,13428',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1727429943',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            21 => 
            array (
                'id' => 25,
                'adid' => 21,
                'describe' => 'm-首页-热游排行榜-热门免费',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '257,234,263,262,229,233,228,226,188',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713343390',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            22 => 
            array (
                'id' => 26,
                'adid' => 22,
                'describe' => 'm-首页-热游排行榜-最受期待',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '160,158,163,167,147,145,144,118,137',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713343434',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            23 => 
            array (
                'id' => 27,
                'adid' => 23,
                'describe' => 'm-首页-应用排行榜-热门免费',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '1,10,2,6,5,3,4,12,11',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713343473',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            24 => 
            array (
                'id' => 28,
                'adid' => 24,
                'describe' => 'm-首页-应用排行榜-最受期待',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '29,33,17,8,9,18,7,32,30',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713343528',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            25 => 
            array (
                'id' => 29,
                'adid' => 20,
                'describe' => 'Astra',
                'url' => 'https://www.apk42.com/game/astra',
                'img' => '52img/uploadimg/20240417/17145940quk1.jpg',
                'status' => 1,
                'remark' => '75',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713343107',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            26 => 
            array (
                'id' => 30,
                'adid' => 20,
                'describe' => 'Blood Strike',
                'url' => 'https://www.apk42.com/game/blood_strike/',
                'img' => '52img/uploadimg/20240417/17155913c2xv.jpg',
                'status' => 1,
                'remark' => '253',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713343131',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            27 => 
            array (
                'id' => 31,
                'adid' => 25,
                'describe' => 'm-游戏详情-好游安利',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '6,7,8,10,312,319,305,254,246,244',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344209',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            28 => 
            array (
                'id' => 32,
                'adid' => 26,
                'describe' => 'm-应用详情-应用安利',
                'url' => '',
                'img' => '',
                'status' => 1,
                'remark' => '4,6,12,1,2,3,29,45,41,19',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344242',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 2,
            ),
            29 => 
            array (
                'id' => 33,
                'adid' => 2,
                'describe' => 'Discover more fun and interesting things',
                'url' => 'https://www.apk42.com/game/brawl_stars',
                'img' => '',
                'status' => 1,
                'remark' => '9',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344570',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            30 => 
            array (
                'id' => 34,
                'adid' => 3,
                'describe' => 'Learn more about game updates',
                'url' => 'https://www.apk42.com/game/astra/',
                'img' => '',
                'status' => 1,
                'remark' => '75',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344589',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            31 => 
            array (
                'id' => 35,
                'adid' => 15,
                'describe' => 'Discover more fun and interesting things',
                'url' => 'https://www.apk42.com/game/astra/',
                'img' => '',
                'status' => 1,
                'remark' => '',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344646',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
            32 => 
            array (
                'id' => 36,
                'adid' => 16,
                'describe' => 'Learn more about game updates',
                'url' => 'https://www.apk42.com/game/brawl_stars',
                'img' => '',
                'status' => 1,
                'remark' => '',
                'no' => 0,
                'uid' => 110,
                'addtime' => '1713344661',
                'hlight' => 2,
                'gid' => NULL,
                'is_del' => 0,
                'type' => 1,
            ),
        ));
        
        
    }
}